-- cX-shop bazasi. Supabase -> SQL Editor -> New query -> butun faylni joylab "Run".
-- Qayta ishga tushirsa ham xavfsiz (bor narsalar buzilmaydi).
--
-- Himoya tamoyili: brauzerda faqat ochiq (anon) kalit bor, kim nima qila olishini
-- quyidagi RLS qoidalari hal qiladi:
--   * mahsulotlar va rasmlar  — hamma ko'ra oladi, faqat admin o'zgartiradi
--   * xabarlar (obunalar)      — faqat admin ko'radi; yozishni api/subscribe.ts (server) qiladi

-- ========== Adminlar ==========
create table if not exists public.admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.admins enable row level security;

drop policy if exists "admin o'zini ko'radi" on public.admins;
create policy "admin o'zini ko'radi" on public.admins
  for select to authenticated using (user_id = auth.uid());

-- joriy foydalanuvchi adminmi? (security definer: admins jadvalini RLS'siz tekshiradi)
-- 2FA yoqilgan admin kodni kiritmaguncha (sessiya 'aal2' bo'lmaguncha) admin hisoblanmaydi:
-- parol o'g'irlansa ham, telefonsiz bazaga yozib bo'lmaydi.
create or replace function public.is_admin() returns boolean
  language sql stable security definer set search_path = public, auth
as $$
  select exists (select 1 from public.admins where user_id = auth.uid())
    and (
      coalesce(auth.jwt() ->> 'aal', 'aal1') = 'aal2'
      or not exists (
        select 1 from auth.mfa_factors f
        where f.user_id = auth.uid() and f.status = 'verified'
      )
    )
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ========== Mahsulotlar ==========
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 200),
  category text not null,
  price numeric(10, 2) not null check (price > 0),
  description text not null default '',
  sizes text[] not null default '{}',
  colors text[] not null default '{}',
  image text,
  tags text[] not null default '{}',
  size_prices jsonb not null default '{}'::jsonb
);
create index if not exists products_created_at_idx on public.products (created_at desc);
-- keyin qo'shilgan ustunlar (eski bazada ham qo'shiladi)
alter table public.products add column if not exists old_price numeric(10, 2) check (old_price > 0);
alter table public.products add column if not exists is_active boolean not null default true;
alter table public.products enable row level security;

-- yashirilgan (is_active = false) mahsulotni faqat admin ko'radi
drop policy if exists "mahsulotlarni hamma ko'radi" on public.products;
create policy "mahsulotlarni hamma ko'radi" on public.products
  for select using (is_active or public.is_admin());

drop policy if exists "faqat admin qo'shadi" on public.products;
create policy "faqat admin qo'shadi" on public.products
  for insert to authenticated with check (public.is_admin());

drop policy if exists "faqat admin o'zgartiradi" on public.products;
create policy "faqat admin o'zgartiradi" on public.products
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "faqat admin o'chiradi" on public.products;
create policy "faqat admin o'chiradi" on public.products
  for delete to authenticated using (public.is_admin());

-- ========== Xabarlar (obunalar) ==========
create table if not exists public.messages (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  type text not null default 'subscribe',
  email text not null,
  device text,
  browser text,
  language text,
  screen text,
  cart jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0,
  is_read boolean not null default false
);
create index if not exists messages_created_at_idx on public.messages (created_at desc);
alter table public.messages enable row level security;

drop policy if exists "xabarlarni faqat admin ko'radi" on public.messages;
create policy "xabarlarni faqat admin ko'radi" on public.messages
  for select to authenticated using (public.is_admin());

drop policy if exists "xabarni faqat admin belgilaydi" on public.messages;
create policy "xabarni faqat admin belgilaydi" on public.messages
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "xabarni faqat admin o'chiradi" on public.messages;
create policy "xabarni faqat admin o'chiradi" on public.messages
  for delete to authenticated using (public.is_admin());
-- insert qoidasi yo'q: brauzerdan to'g'ridan yozib bo'lmaydi, faqat server (service_role)

-- ========== Buyurtmalar ==========
-- Do'kondagi "Оформить заказ" -> api/order.ts (server narxni bazadan o'zi hisoblaydi) -> shu jadval
create table if not exists public.orders (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default now(),
  status text not null default 'new'
    check (status in ('new', 'processing', 'shipped', 'delivered', 'cancelled')),
  customer_name text not null check (char_length(customer_name) between 2 and 100),
  phone text not null,
  email text,
  address text not null,
  comment text,
  items jsonb not null default '[]'::jsonb,
  total numeric(10, 2) not null default 0,
  admin_note text,
  device text,
  browser text
);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
alter table public.orders enable row level security;

drop policy if exists "buyurtmani faqat admin ko'radi" on public.orders;
create policy "buyurtmani faqat admin ko'radi" on public.orders
  for select to authenticated using (public.is_admin());

drop policy if exists "buyurtmani faqat admin o'zgartiradi" on public.orders;
create policy "buyurtmani faqat admin o'zgartiradi" on public.orders
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "buyurtmani faqat admin o'chiradi" on public.orders;
create policy "buyurtmani faqat admin o'chiradi" on public.orders
  for delete to authenticated using (public.is_admin());
-- insert qoidasi yo'q: faqat server (service_role) yozadi

-- ========== Mahsulot rasmlari (Storage) ==========
-- ochiq (hamma ko'radi), bitta fayl 2 MB gacha, faqat rasm turlari
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 2097152,
        array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "rasmni faqat admin yuklaydi" on storage.objects;
create policy "rasmni faqat admin yuklaydi" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "rasmni faqat admin o'zgartiradi" on storage.objects;
create policy "rasmni faqat admin o'zgartiradi" on storage.objects
  for update to authenticated
  using (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "rasmni faqat admin o'chiradi" on storage.objects;
create policy "rasmni faqat admin o'chiradi" on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-images' and public.is_admin());

-- ========== Sayt sozlamalari (bosh sahifa sarlavhasi, matni, rasmi) ==========
-- Har doim bitta qator (id = 1). Bo'sh (null) maydon -> saytda standart qiymat.
create table if not exists public.site_settings (
  id int primary key default 1 check (id = 1),
  hero_title text check (char_length(hero_title) <= 80),
  hero_subtitle text check (char_length(hero_subtitle) <= 240),
  hero_image text,
  updated_at timestamptz not null default now()
);
insert into public.site_settings (id) values (1) on conflict (id) do nothing;
alter table public.site_settings enable row level security;

drop policy if exists "sozlamalarni hamma ko'radi" on public.site_settings;
create policy "sozlamalarni hamma ko'radi" on public.site_settings
  for select using (true);

drop policy if exists "sozlamalarni faqat admin o'zgartiradi" on public.site_settings;
create policy "sozlamalarni faqat admin o'zgartiradi" on public.site_settings
  for update to authenticated using (public.is_admin()) with check (public.is_admin());

-- ========== Admin akkauntini qo'shish ==========
-- 1) Authentication -> Users -> "Add user" -> email + parol ("Auto Confirm User" belgilang)
-- 2) Authentication -> Sign In / Providers -> "Allow new users to sign up" ni O'CHIRING
-- 3) Authentication -> URL Configuration -> Redirect URLs ga admin manzilini qo'shing,
--    masalan https://cx-shop-admin.vercel.app/reset  ("Забыли пароль?" xati shu yerga olib keladi)
-- 4) Quyidagi qatordagi emailni o'zingiznikiga almashtirib, alohida ishga tushiring:
--
-- insert into public.admins (user_id)
-- select id from auth.users where email = 'SIZNING@EMAIL.COM'
-- on conflict do nothing;
